//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demka.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovar()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
        
        public string BackgroundColor
        {
            get
            {
                return (discount.HasValue && discount.Value > 12) ? "#F4A460" : "White";
            }
        }

        public int tovarId { get; set; }
        public string articul { get; set; }
        public string name { get; set; }
        public Nullable<int> unitId { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> supplierId { get; set; }
        public Nullable<int> manufacturerId { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<int> quantity { get; set; }
        public string description { get; set; }
        public string image { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
